//@version=5
strategy("Bollinger Bands Strategy", overlay=true)

source = close

length = input.int(title="BBands length", 8, minval=1)
mult = input.float(title="BBands multiplier", 1.76, minval=0.001, maxval=50)
fast_length = input(title="Fast Length", defval=12)
slow_length = input(title="Slow Length", defval=26)
signal_length = input.int(title="Signal Smoothing",  minval = 1, maxval = 50, defval = 9)
hist_smooth = input(title="Hist EMA Length", defval=9)
sma_source = input.string(title="Oscillator MA Type",  defval="EMA", options=["SMA", "EMA"])
sma_signal = input.string(title="Signal Line MA Type", defval="EMA", options=["SMA", "EMA"])



fast_ma = sma_source == "SMA" ? ta.sma(src, fast_length) : ta.ema(src, fast_length)
slow_ma = sma_source == "SMA" ? ta.sma(src, slow_length) : ta.ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal == "SMA" ? ta.sma(macd, signal_length) : ta.ema(macd, signal_length)
hist = macd - signal
emahist = sma_source == "SMA" ? ta.sma(hist, hist_smooth) : ta.ema(hist, hist_smooth)



basis = ta.ema(source, length)
// basis2 = ta.ema(source, math.round(length*1.618))
dev = mult * ta.stdev(source, length)
// dev2 = mult * ta.stdev(source, math.round(length*1.618))
// upper_1= basis + (0.236*dev)+1
// upper_2= basis + (0.382*dev)+1
// upper_3= basis + (0.5*dev)+1
upper= basis + dev
// upper_4= basis + (0.618*dev)+1
// upper_5= basis + (0.764*dev)+1
// upper_6= basis + (1*dev)+1
// lower_1= basis - (0.236*dev)-1
// lower_2= basis - (0.382*dev)-1
// lower_3= basis - (0.5*dev)-1
lower= basis - dev
// lower_4= basis - (0.618*dev)-1
// lower_5= basis - (0.764*dev)-1
// lower_6= basis - (1*dev)-1
// upper_12= basis2 + (0.236*dev2)+1
// upper_22= basis2 + (0.382*dev2)+1
// upper_32= basis2 + (0.5*dev2)+1
// lower_12= basis2 - (0.236*dev2)-1
// lower_22= basis2 - (0.382*dev2)-1
// lower_32= basis2 - (0.5*dev2)-1


// ta.rising()
buyEntry = ta.crossunder(low, lower) and 
sellEntry = ta.crossunder(high, upper)
if (ta.crossunder(low, lower)) and 
	strategy.entry("BBandLE", strategy.long, stop=upper, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandLE")
else
	strategy.cancel(id="BBandLE")
if (ta.crossover(high, upper))
	strategy.entry("BBandSE", strategy.short, stop=lower, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandSE")
else
	strategy.cancel(id="BBandSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)




